version: "3.8"

services:
  mysql-server:
    image: mysql:8
    container_name: nodejs15-mysql-server
    ports:
      - "4500:3306"
    restart: unless-stopped
    environment:
      MYSQL_USER: sergio
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: cursodb
    volumes:
      - vol-nodejs15-mysql:/var/lib/mysql
    networks:
      - nodejs15-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 8s

  mysql-client:
    image: phpmyadmin
    container_name: nodejs15-mysql-client
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - nodejs15-mysql-network
    depends_on:
      mysql-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 8s

volumes:
  vol-nodejs15-mysql:
    name: vol-nodejs15-mysql

networks:
  nodejs15-mysql-network:
    name: nodejs15-mysql-network
    driver: bridge
