### Login
POST http://35ad-38-25-16-159.ngrok-free.app/v1/auth/login
content-type: application/json

{
    "email": "sergio26@correo.com",
    "password": "Mundo2023"
}

### Login Cloud
POST http://app-docker-single-container-prod.us-east-1.elasticbeanstalk.com/v1/auth/login
content-type: application/json

{
    "email": "sergio26@correo.com",
    "password": "Mundo2023"
}



### Login invalid
POST http://localhost:3000/v1/auth/login
content-type: application/json

{
    "email": "sergio26@correodddddd.com",
    "password": "Mundo2023"
}

### Get new access token
GET http://localhost:3000/v1/auth/new-access-token?refreshToken=0363b818-02ae-4a80-8fe0-223a8dbd4475


