### Crear un usuario
POST http://localhost:3000/v1/user
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiU2VyZ2lvIiwiaW1hZ2UiOiJodHRwczovL25vZGVqczE1LWltYWdlcy5zMy5hbWF6b25hd3MuY29tL2E1Yzk3ZGVmLWVjOGQtNDhmYy05YmUyLWNlMTJiOTg2YWNiNy5qcGciLCJyb2xlcyI6WyJURUFDSEVSIiwiQURNSU4iXSwiaWF0IjoxNzA0MjQ1MDA1MzE5LCJleHAiOjE3MDQyNDUzMDUzMTl9.8RIz5Ai91hmVV-V-dMscJroQd2YN91dp0tFP0zyD4To

{
    "id": "289be435-991e-49be-8540-41304a993e14",
    "name": "José Luis",
    "lastname": "Hidalgo",
    "email": "sergio27@correo.com",
    "password": "Mundo2023",
    "age": 23,
    "gender": "HOMBRE",
    "address": {
        "street": "Calle 1",
        "number": 123,
        "city": "Bogota",
        "country": "Colombia"
    },
    "image": "a5c97def-ec8d-48fc-9be2-ce12b986acb7.jpg",
    "roles": [{"id": "dd48a1da-e11a-41c7-a16c-2e48189045e0"}, {"id": "91166239-f259-4d0e-ba72-b105557e6753"}]
}

### Listar los usuarios
GET http://localhost:3000/v1/user
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiU2VyZ2lvIiwiaW1hZ2UiOiJodHRwczovL25vZGVqczE1LWltYWdlcy5zMy5hbWF6b25hd3MuY29tL2E1Yzk3ZGVmLWVjOGQtNDhmYy05YmUyLWNlMTJiOTg2YWNiNy5qcGciLCJyb2xlcyI6WyJURUFDSEVSIiwiQURNSU4iXSwiaWF0IjoxNzA0MjQzOTY2MzE0LCJleHAiOjE3MDQyNDQwMTYzMTR9._rNmVLKOkXcP3WKQv1n96ejioYTzKxPvt7L9TAeuEgM

### Obtener un usuario
GET http://localhost:3000/v1/user/6f2a6a96-e4d6-43c5-b470-2cd411b1da36

### Actualizar un usuario
PUT http://localhost:3000/v1/user/6f2a6a96-e4d6-43c5-b470-2cd411b1da36
content-type: application/json

{
    "name": "Sergio",
    "lastname": "Hidalgo",
    "password": "Mundo2023",
    "age": 40,
    "gender": "HOMBRE",
    "address": {
        "street": "Calle 1",
        "number": 123,
        "city": "Bogota",
        "country": "Colombia"
    },
    "image": "a5c97def-ec8d-48fc-9be2-ce12b986acb7.jpg",
    "roles": [{"id": "dd48a1da-e11a-41c7-a16c-2e48189045e0"}, {"id": "91166239-f259-4d0e-ba72-b105557e6753"}, {"id": "03397abb-6022-4324-a8c5-027690a5e0de"}]
}


### Eliminar un usuario
DELETE http://localhost:3000/v1/user/6f2a6a96-e4d6-43c5-b470-2cd411b1da36

### Obtener por página
GET http://localhost:3000/v1/user/page?page=0&limit=2